### ISSUE TITLE
ModuleNotFoundError: No module named 'datascience'

### ISSUE THREAD

**Issue by flavio-araujo** [Mashimo/datascience#1]
Tryied to run on https://mybinder.org/v2/gh/ipython/ipython-in-depth/master?filepath=binder%2FIndex.ipynb and I´m getting the following error:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d249dfdea9a7> in <module>()
      1 import matplotlib.pyplot as plt
----> 2 from datascience import stats
      3 
      4 agePhysics = [25,31,31,31,31,32,33,34,35,35,35,35,35,36,36,37,37,37,37,37,38,38,38,39,39,
      5               40,40,40,40,40,41,42,42,42,42,42,42,42,42,43,43,43,43,44,44,44,44,44,44,45,

ModuleNotFoundError: No module named 'datascience'

**Comment by Mashimo** [comment]
You can get the module directly from github: https://github.com/Mashimo/datascience/tree/master/datascience
or you can comment out all the parts related to 'stats': they are not mandatory for that example
